'use client';

import React, { ReactNode, Suspense } from 'react';

import { Button } from '@heroui/button';
import { InputOtp } from '@heroui/input-otp';
import { Modal, ModalBody, ModalContent, ModalFooter, ModalHeader } from '@heroui/modal';
import { zodResolver } from '@hookform/resolvers/zod';
import { Controller, useForm } from 'react-hook-form';

import { description } from '@/components/primitives';
import { otpSchema, OtpSchema } from '@/lib/zod';

interface OwnProps {
    isOpen: boolean;
    loading: boolean;

    title?: ReactNode;
    description?: ReactNode;

    onClose: () => void;
    onSubmit: (v: any) => void;
}

const defaultTitle = 'Enter Verification Code';
const defaultDescription = 'To complete this action, please enter the 2FA code generated by your authentication app. This additional layer of security helps keep your account safe.';

export const TwoFactorModal: React.FC<OwnProps> = (props) => {
    const { isOpen, title = defaultTitle, description: des = defaultDescription, loading, onClose, onSubmit } = props;

    const { handleSubmit, control, reset } = useForm<OtpSchema>({
        resolver: zodResolver(otpSchema),
        defaultValues: {
            otp: '',
        },
    });

    const onCloseModal = () => {
        reset();
        onClose();
    };

    return (
        <Modal backdrop="opaque" isOpen={isOpen} size="sm" onClose={onCloseModal}>
            <ModalContent>
                <form autoComplete="off" method="POST" onSubmit={handleSubmit(onSubmit)}>
                    <ModalHeader className="flex flex-col gap-2">
                        <h4>{title}</h4>
                        <p className={description({ className: 'font-normal m-0', size: 'xs' })}>{des}</p>
                    </ModalHeader>
                    <ModalBody>
                        <Controller
                            control={control}
                            name="otp"
                            render={({ field, formState }) => (
                                <InputOtp
                                    classNames={{ segmentWrapper: 'gap-2' }}
                                    color="default"
                                    errorMessage={formState.errors?.otp?.message}
                                    isInvalid={!!formState.errors?.otp?.message}
                                    length={6}
                                    validationBehavior="aria"
                                    variant="flat"
                                    onComplete={onSubmit}
                                    onInput={field.onChange}
                                />
                            )}
                        />
                    </ModalBody>
                    <ModalFooter className="mt-4 border-t border-default">
                        <Suspense>
                            <Button
                                color="primary"
                                isDisabled={loading}
                                isLoading={loading}
                                type="submit"
                            >
                                Submit
                            </Button>
                        </Suspense>
                    </ModalFooter>
                </form>
            </ModalContent>
        </Modal>
    );
};
