'use client';

import React, { Suspense } from 'react';
import { Button } from '@heroui/button';
import { Modal, ModalBody, ModalContent, ModalFooter, ModalHeader } from '@heroui/modal';
import { Controller } from 'react-hook-form';

import { description } from '@/components/primitives';
import { InputOtp } from '@/lib/otpInput';

interface OwnProps {
    control: any;
    isOpen: boolean;
    onClose: () => void;
    onSubmit: () => void;
    isCtaLoading: boolean;
    isCtaDisabled: boolean;
}

export const TwoFactorAuthModal: React.FC<OwnProps> = (props) => {
    const { control, isOpen, isCtaDisabled, isCtaLoading, onClose, onSubmit } = props;

    return (
        <Modal backdrop="blur" isDismissable={false} isOpen={isOpen} onClose={onClose}>
            <ModalContent>
                <ModalHeader className="mb-2 flex flex-col gap-1 ">
                    <h4>Enter Verification Code</h4>
                    <p className={description({ className: 'font-normal', size: 'xs' })}>
                        To complete your login, please enter the 2FA code generated by your authentication app.
                        This additional layer of security helps keep your account safe.
                    </p>
                </ModalHeader>
                <ModalBody>
                    <Controller
                        control={control}
                        name="otp"
                        render={({ field, formState }) => (
                            <InputOtp
                                classNames={{ segmentWrapper: 'justify-between', base: 'w-full' }}
                                color={!!formState.errors?.otp?.message ? 'danger' : 'default'}
                                errorMessage={formState.errors?.otp?.message?.toString()}
                                otplength={6}
                                radius="md"
                                variant="faded"
                                onFill={onSubmit}
                                onInput={field.onChange}
                            />
                        )}
                    />
                </ModalBody>
                <ModalFooter className="mt-4 border-t border-default">
                    <Suspense>
                        <Button
                            color="primary"
                            isDisabled={isCtaDisabled}
                            isLoading={isCtaLoading}
                            type="submit"
                            onPress={onSubmit}
                        >
                            Submit
                        </Button>
                    </Suspense>
                </ModalFooter>
            </ModalContent>
        </Modal>
    );
};
